-- Table to store data from the exchange
CREATE TABLE Stock_Ownership_Exchange (
    User_ID      NUMBER,
    Stock_ID     VARCHAR2(10),
    Stock_Name   VARCHAR2(50),
    Stock_Count  NUMBER,
    PRIMARY KEY (User_ID, Stock_ID)
);

-- Table to store data from the depository
CREATE TABLE Stock_Ownership_Depository (
    User_ID      NUMBER,
    Stock_ID     VARCHAR2(10),
    Stock_Name   VARCHAR2(50),
    Stock_Count  NUMBER,
    PRIMARY KEY (User_ID, Stock_ID)
);

-- Table to log comparison results
CREATE TABLE Stock_Ownership_Comparison_Log (
    Log_ID       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    User_ID      NUMBER,
    Stock_ID     VARCHAR2(10),
    Stock_Name   VARCHAR2(50),
    Exchange_Count  NUMBER,
    Depository_Count NUMBER,
    Comparison_Result VARCHAR2(50),
    Comparison_Date   DATE DEFAULT SYSDATE
);

-- Package Specification
CREATE OR REPLACE PACKAGE stock_comparison_pkg AS
    -- Procedure to load CSV data into database tables
    PROCEDURE load_exchange_data(file_path IN VARCHAR2);
    PROCEDURE load_depository_data(file_path IN VARCHAR2);
    
    -- Procedure to compare data between exchange and depository
    PROCEDURE compare_stock_ownership;
    
    -- Utility to log results
    PROCEDURE log_comparison_result(user_id IN NUMBER, stock_id IN VARCHAR2, stock_name IN VARCHAR2, 
                                    exchange_count IN NUMBER, depository_count IN NUMBER, 
                                    comparison_result IN VARCHAR2);
END stock_comparison_pkg;
/

-- Package Body
CREATE OR REPLACE PACKAGE BODY stock_comparison_pkg AS

    -- Procedure to load data from exchange CSV file
    PROCEDURE load_exchange_data(file_path IN VARCHAR2) IS
    BEGIN
        -- Assuming external tables or some file-loading mechanism
        DBMS_OUTPUT.PUT_LINE('Loading data from exchange file: ' || file_path);
    END load_exchange_data;
    
    -- Procedure to load data from depository CSV file
    PROCEDURE load_depository_data(file_path IN VARCHAR2) IS
    BEGIN
        -- Assuming external tables or some file-loading mechanism
        DBMS_OUTPUT.PUT_LINE('Loading data from depository file: ' || file_path);
    END load_depository_data;
    
    -- Procedure to compare stock ownership between exchange and depository
    PROCEDURE compare_stock_ownership IS
        CURSOR c_comparison IS
            SELECT e.User_ID, e.Stock_ID, e.Stock_Name, e.Stock_Count AS Exchange_Count,
                   d.Stock_Count AS Depository_Count
              FROM Stock_Ownership_Exchange e
              JOIN Stock_Ownership_Depository d
                ON e.User_ID = d.User_ID
               AND e.Stock_ID = d.Stock_ID;
               
        v_comparison_result VARCHAR2(50);
    BEGIN
        FOR r IN c_comparison LOOP
            -- Compare stock counts between exchange and depository
            IF r.Exchange_Count = r.Depository_Count THEN
                v_comparison_result := 'MATCH';
            ELSE
                v_comparison_result := 'MISMATCH';
            END IF;
            
            -- Log the result of the comparison
            log_comparison_result(r.User_ID, r.Stock_ID, r.Stock_Name, 
                                  r.Exchange_Count, r.Depository_Count, v_comparison_result);
        END LOOP;
    END compare_stock_ownership;

    -- Procedure to log comparison results
    PROCEDURE log_comparison_result(user_id IN NUMBER, stock_id IN VARCHAR2, stock_name IN VARCHAR2, 
                                    exchange_count IN NUMBER, depository_count IN NUMBER, 
                                    comparison_result IN VARCHAR2) IS
    BEGIN
        INSERT INTO Stock_Ownership_Comparison_Log (User_ID, Stock_ID, Stock_Name, 
                                                    Exchange_Count, Depository_Count, 
                                                    Comparison_Result)
        VALUES (user_id, stock_id, stock_name, exchange_count, depository_count, comparison_result);
        COMMIT;
    END log_comparison_result;

END stock_comparison_pkg;
/


-- Load Data
stock_comparison_pkg.load_exchange_data('exchange_data.csv');
stock_comparison_pkg.load_depository_data('depository_data.csv');

-- Compare Ownership
EXEC stock_comparison_pkg.compare_stock_ownership;

-- Show Results
SELECT * FROM Stock_Ownership_Comparison_Log;